api_token: "seq-trialapikey"
project_name: test_project
url: "http://0.0.0.0:8000/" #local host url where seqtra rag is running
file_dir: "./Files"
query: "How can the Board and the CCO manage control functions?"
num_seed_nodes: 1
chunk_only: true
strategy: "graph_extended"
