api_token: Your Seqtra API key
project_name: test_project
url: http://0.0.0.0:8000/
llm: claude
llm_key: Your Claude API Key
file_dir: ./Files
query: How can the Board and the CCO manage control functions?
num_seed_nodes: 1
chunk_only: false
strategy: graph_extended
